version: '3.6'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3002:3002
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=localhost
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db_user
    networks:
      - lendit_gateway
  db_user:
    image: postgres:13.2-alpine
    ports:
      - 5105:5432
    volumes:
      - ./src/db/scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - lendit_gateway

networks:
  lendit_gateway:
    external: true
    driver: 'bridge'
