version: "3.6"

services:
  gateway-service:
    build:
        context: .
        dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3002
      - 9229:9229
    command: /bin/sh -c "npm install && npm run dev"
